version: "3.1"

services:
  npm:
    image: node:14
    container_name: npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  frontend:
    image: panbanglanfeng/fanshawe-ims:mevn_frontend
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${FE_PORT}:8080
    environment:
      VUE_APP_API_PORT: ${BE_PORT}  